---
# --- Metadatos Básicos ---
title: "Análisis Descriptivo de la Productividad Agrícola en Distintas Regiones de la India Durante el Periodo 1997-2020"
author:
   - Asly Caputo
   - Aymara Andersen
   
date: "Marzo 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  El presente informe elabora un análisis estadístico descriptivo sobre la producción y rendimiento agrícola en distintas regiones de la India. Donde se busca estudiar el comportamiento de la producción y rendimiento de varios tipos de cultivos agrícolas, a nivel temporal, geográfico y general, aplicando técnicas estadísticas descriptivas y visualización de datos con R.
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
```

\chapter*{Introducción}

La agricultura es una de las actividades económicas más cruciales en la economía de cualquier país produciendo alimentos, materias primas y generando empleos a gran parte de la población. Asimismo, la India alberga una de las economías agrícolas más grandes del mundo con el 7,5% de la producción agrícola a nivel global, convirtiéndose en uno de los principales países productores agrícolas del mundo.\

A causa de esto, resulta de interés investigar estadísticamente el comportamiento del sector agrícola relacionado con la producción y rendimiento de varios cultivos en la India para responder algunas interrogantes de interés como:\

\textbf{1.} ¿Cuáles son las regiones con mayor y menor producción agrícola?\

\textbf{2.} ¿Cómo ha evolucionado la producción y rendimiento a través del tiempo?\

\textbf{3.} ¿Cómo afecta el tipo de cultivo en el área cultivada?\

Por eso, el presente estudio tiene como finalidad realizar un análisis estadístico descriptivo del conjunto de datos “rendimiento de los cultivos agrícolas en los estados de la India” que abarca datos agrícolas de múltiples cultivos plantados en varios estados de la India desde 1997 hasta 2020. Haciendo uso de herramientas para el análisis de datos del lenguaje de programación R y de técnicas de visualización de datos.\

\section*{Estructura de Informe}

\begin{itemize}

    \item \textbf{Capítulo I}, se define el enfoque y propósito del estudio, planteando la problemática del estudio, formulando las preguntas de la investigación, determinando el contexto, límites y objetivos del problema a investigar.
    
    \item \textbf{Capítulo II}, se establecen las bases teóricas necesarias para entender cómo abordar el problema de estudio, definiendo conceptos primordiales para la investigación y las técnicas estadísticas necesarias para la resolución del problema.
    
    \item \textbf{Capítulo III}, se describe la metodología utilizada para el análisis de los datos del estudio, esto incluye la descripción detallada del proceso de limpieza de datos (ETL) y las técnicas usadas para la validación de los datos.
    
    \item \textbf{Capítulo IV}, se realiza la exposición de los resultados del análisis, respondiendo a las interrogantes de la investigación planteadas en el capítulo I haciendo uso de distintas técnicas de visualización  de datos como tablas y gráficos.
    
    \item \textbf{Capítulo V}, se muestran las conclusiones y recomendaciones basadas en el análisis de los resultados expuestos.
    
\end{itemize}

Este estudio busca entender las características del sector agrícola de uno de los principales países productores agrícolas del mundo, analizando su avance y evolución a través del tiempo.

\chapter{Planteamiento del Problema}

La agricultura ha sido un sector económico de la India que ha ido evolucionando a través del tiempo, siendo actualmente uno de los países con mayor producción agrícola a nivel global, lo que lo hace uno de los sectores económicos más relevantes del país. Sin embargo, la agricultura también es un sector con una alta variabilidad cuando hablamos de rendimiento, dependiendo de factores como el tipo de cultivo sembrado y la zona geográfica en la que se encuentra, por lo que obtener una alta producción requiere de un análisis exhaustivo para obtener los mejores resultados.\

A nivel económico, la variabilidad del sector agrícola puede suponer un riesgo significativo a la hora de invertir en este sector, por lo que es necesario un estudio como mínimo la compatibilidad entre la región y el tipo de cultivo escogidos, así como su evolución a través del tiempo.\

Por eso, resulta de interés analizar estadísticamente el comportamiento y rendimiento de la producción agrícola en la India a nivel general, temporal y geográfico, ya que, independientemente de su gran nivel de producción, es necesario saber la distribución del sector para definir concretamente cual es el sitio más óptimo de inversión.\

A partir de esto, se plantean las siguientes preguntas de investigación:\

\textbf{1.} ¿Cuáles son las regiones con mayor y menor producción agrícola?\

\textbf{2.} ¿Cómo ha evolucionado la producción y rendimiento a través del tiempo?\

\textbf{3.} ¿Cómo afecta el tipo de cultivo en el área cultivada?\

\section{Justificación}

El presente estudio tiene como justificación la necesidad de conocer e identificar estadísticamente la rentabilidad agrícola de una determinada zona únicamente con los factores básicos que afectan la producción agrícola, sin necesidad de tener un conocimiento profundo del área, lo que permite la toma rápida de mejores decisiones.\

Desde un punto estadístico, el explorar y analizar la variabilidad de este sector ayuda a manejar técnicas del análisis descriptivo, haciendo uso de herramientas tecnológicas como lo son los lenguajes R y Python.

\section{Objetivos}

\subsection{Objetivo General}

Realizar un análisis descriptivo de la producción, área cultivada y rendimiento agrícola de las regiones de la India durante el periodo 1997-2020.

\subsection{Objetivos Específicos}

\begin{itemize}
  \item{Comparar la producción, área y rendimiento agrícolas total de la India durante todo el periodo de estudio.}
  \item{Determinar la variabilidad de la producción, área y rendimiento agrícolas de cada región de la India durante el lapso de estudio.}
  \item{Identificar el impacto que tiene el área de cultivo según su tipo.}
  \item{Evaluar los cambios en la evolución histórica de la producción, área y rendimiento agrícola durante el periodo 1997-2020.}
  \item{Cuantificar la relación de la producción de las regiones de la India y los tipos de cultivos.}
\end{itemize}

\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal abarca las características de cada cultivo registrado y distribuidas en 10 columnas, donde se consideran las dimensiones descriptivas del cultivo y las métricas del rendimiento junto con su relación entre diversos factores agronómicos.\

\begin{table}[ht]
\centering
\caption{Variables consideradas en el estudio} 
\resizebox{12cm}{!} {
\begin{tabular}{cll}
  \hline
  \textbf{TIPO} & \textbf{VARIABLE} & \textbf{DESCRIPCIÓN} \\ 
  \hline
  Categórica & Crop & Nombre del cultivo. \\ 
  Númerica & Crop\_Year & El año en el que se sembró el cultivo. \\ 
  Categórica & Season & Temporada de cultivo específica (ej: Kharif, Rabí, Whole Year). \\ 
  Categórica & State & Estado de la India donde se sembró el cultivo. \\ 
  Númerica & Area & Superficie total de tierra (en hectáreas) cultivada. \\ 
  Númerica & Production & Cantidad de producción agrícola (en toneladas métricas) \\ 
  Númerica & Annual\_Rainfall & La precipitación anual recibida en la región de cultivo (en mm) \\ 
  Númerica & Fertilizer & Cantidad total de fertilizante utilizado para el cultivo (en kilogramos) \\ 
  Númerica & Pesticide & Cantidad total de pesticida utilizado para el cultivo (en kilogramos). \\ 
  Númerica & Yield & Rendimiento calculado del cultivo (producción por unidad de área). \\ 
   \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

La cobertura vertical del trabajo de investigación abarca un total de 19,698 observaciones (registros) donde cada fila representa un cultivo específico y sus características correspondientes, con un alcance temporal que abarca desde el año 1997 hasta el año 2020.

\section{Periodo de Referencia}

La fuente de datos a estudiar corresponde al repositorio abierto de Kaggle (“Agricultural Crop Yield in Indian States Dataset”). Donde se toma como período de referencia los registros pertenecientes al intervalo de tiempo 1997-2020.

\section{Variables}

Para este estudio, se tomaron en cuenta como variables principales Production, Area y Yield, las cuales representan la toneladas producidas, las hectáreas cultivadas y su producción por área respectivamente.\

También se tomaron como variables explicativas:

\begin{enumerate}
  \item Variables Temporales: \textbf{Crop\_Year}
  \item Variables Categóricas: \textbf{Crop}
  \item Variables Geográficas: \textbf{State}
\end{enumerate}

\chapter{Marco Teórico}

\section{Bases Teóricas}

En este capítulo se desarrollarán los conceptos y fundamentos estadísticos necesarios para realizar el análisis estadístico necesario para cubrir los objetivos planteados anteriormente. Se abordarán conceptos como la tipología de cultivos, regiones agrícolas de la India y las medidas fundamentales para la Estadística descriptiva Univariante y Bivariante.

Estos conceptos son necesarios para comprender la metodología y resultados de análisis de este estudio y asociarlos al entorno agrícola de la investigación.\

\subsection{Tipología de Cultivos}

La India diversifica su producción para satisfacer tanto el mercado interno como el global, en este estudio se analizan 50 variedades de cultivos, por lo que agruparlos puede resultar útil para algunos análisis específicos:

\begin{itemize}
 \item{\textbf{Cultivos Alimentarios:} Cereales y legumbres que forman la dieta básica. La India es líder mundial en la producción de legumbres (fuente principal de proteína para su población mayoritariamente vegetariana).}
 \item{\textbf{Cultivos de Plantación:} Introducidos en gran medida durante la época colonial, se cultivan en grandes fincas para exportación. Destacan el té (Assam y Darjeeling), el café (Karnataka) y el caucho (Kerala).}
 \item{\textbf{Cultivos Industriales o Comerciales:} Materias primas para la industria manufacturera. La caña de azúcar para el azúcar y el etanol, y el algodón para la potente industria textil india.}
 \item{\textbf{Horticultura:} Incluye frutas, flores y especias. La India es el mayor productor mundial de especias (pimienta, cardamomo, cúrcuma) y mangos.}
\end{itemize}

\

\subsection{Regiones Agrícolas de la India}

El país se puede dividir en zonas productivas clave, para el estudio, saber las zonas productivas nos da un indicio de cuáles cultivos pueden tener máyor producción en algunos estados que otras:

\begin{itemize}

    \item{\textbf{Región del Noroeste (Punjab, Haryana):} Es la zona más tecnificada y rica. Produce la mayor parte del trigo y arroz del país.}
    \item{\textbf{Valle del Ganges y Brahmaputra:} Suelos aluviales extremadamente fértiles. Es el reino del arroz, el yute y la caña de azúcar.}
    \item{\textbf{Cinturón de Suelo Negro (Maharashtra, Gujarat):} Conocido como la "región del algodón". El suelo retiene muy bien la humedad, ideal para cultivos de fibra.}
    \item{\textbf{Zonas de Plantación del Sur y Noreste:} Las colinas de los Ghats Occidentales y Assam, donde el clima húmedo y la altitud permiten el cultivo de té, café y especias}
    \item{\textbf{Zonas Áridas (Rajasthan):} Se especializan en mijos y semillas oleaginosas que requieren mínima agua.}

\end{itemize}

\

\subsection{Estadística Descriptiva Univariante}

La estadística descriptiva univariante se centra en el análisis de datos, haciendo uso de herramientas para describir, tabular, representar y visualizar el comportamiento de una variable.

Para este estudio, será necesario entender el comportamiento individual de la producción, el área cultivada y el rendimiento anual utilizando técnicas de la estadística descriptiva univariante.\

\\subsubsection\*{Medidas de Posición}

Las medidas de posición, también llamadas fractiles o cuantiles, son utilizadas para facilitar la localización de un dato respecto de un conjunto de ellos. Para este estudio, se utilizarán:

\begin{itemize}
\item{\textbf{Cuartiles:} Valores que dividen la serie en 4 partes iguales, cada una de ellas con un 25\% de los datos.}

$$P_k = \frac{k(n + 1)}{4}$$

\item{\textbf{Mediana:} Promedio no matemático que divide a la serie de datos de un estudio, en dos partes iguales, que representan cada una el 50\% de los datos.}

$$Me = \left(\frac{n+1}{2}\right)$$
\end{itemize}

\

\\subsubsection\*{Medidas de Tendencia Central}

Son casos especiales de las medidas de posición, debido a su ubicación en la zona central de la distribución. Estas medidas, también son denominadas promedios.

\begin{itemize}
\item{\textbf{Media Aritmética:} Es el valor resultante más “representativo” de la serie de datos, el punto de equilibrio, el centro de gravedad de la serie.}

$$\bar{x} = \frac{\sum_{i=1}^{n} x_i}{n}$$

\item{\textbf{Mediana:} Promedio no matemático que divide a la serie de datos de un estudio, en dos partes iguales, que representan cada una el 50\% de los datos.}

 $$Me = \left(\frac{n+1}{2}\right)$$

\item{\textbf{Moda:} Es un promedio no matemático representado por el valor con mayor número de ocurrencias dentro de la serie de datos.}
\end{itemize}

\

\\subsubsection\*{Medidas de Dispersión}

Tienen por objeto medir la magnitud de los desvíos de los valores de la variable con respecto al valor central de la distribución, es decir, definen cuán semejante o cuán distinto son cada uno de los valores, de la variable con respecto al valor central.

\begin{itemize}
\item{\textbf{Rango Intercuartílico:} constituye la máxima diferencia posible entre dos valores entre el 50\% de los datos centrales.}

$$IQR = Q_3 - Q_1$$

\item{\textbf{Varianza:} Es el promedio cuadrático de los desvíos de los datos respecto de la media aritmética.}

$$\sigma^2 = \frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}$$

\item{\textbf{Desviación Típica:} Es la raíz cuadrada positiva de la varianza. Constituye el índice de dispersión más usado y más confiable.}

$$s = \sqrt{s^2} = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n}}$$

\item{\textbf{Coeficiente de Variación de Pearson:} Es el cociente entre la desviación estándar y la media aritmética, multiplicado por cien. Es el coeficiente de dispersión relativa de más amplio uso.}

$$CV =  \frac{s}{\bar{x}} \times 100\%$$
\end{itemize}

\

\subsection{Estadística Descriptiva Bivariante}

La estadística descriptiva bivariante analiza la relación entre dos variables donde se busca resumir y describir la información conjunta de ambos conjuntos de datos, para identificar patrones y tendencias

En este estudio resulta de interés conocer a fondo el tipo de relación que hay entre cada una de las variables, tanto numéricas como categóricas, para saber la influencia que tienen una sobre a otra.\

\\subsubsection\*{Medidas de Dispersión Conjunta}

\begin{itemize}
\item{\textbf{Coeficiente de Correlación de Pearson:} Es una medida que da cuenta del sentido, dirección e intensidad o magnitud de la relación lineal entre dos variables cuantitativas.}

$$r = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{n\cdot\sqrt{\sum_{i=1}^{n}) (x_i - \bar{x})^2} \cdot \sqrt{\sum_{i=1}^{n} (y_i - \bar{y})^2}}$$
\end{itemize}

\

\subsection{Método de Detección de Datos Atípicos}
\subsubsection*{Prueba de Tukey}

verifica múltiples valores atípicos en ambos lados, categorizados como valores “externos” o “muy alejados”. En este caso los límites son:

\begin{itemize}
\item{\textbf{Límites internos:} Se consideran atípicas leves aquellas observaciones alejadas del 1er y 3er cuartil, respectivamente, más 1,5 veces el Recorrido Intercuartílico.}

$$X_i \le Q_1 - 1,5RI \quad \text{o} \quad X_i \ge Q_3 + 1,5RI$$

\item{\textbf{Límites externos:} Se consideran atípicas extremas aquellas observaciones alejadas del 1er y 3er cuartil, respectivamente, más de 3 veces el Recorrido Intercuartílico.}

$$X_i \le Q_1 - 3RI \quad \text{o} \quad X_i \ge Q_3 + 3RI$$
\end{itemize}

\

\subsection{Series de Tiempo}

Las series de tiempo son una herramienta gráfica ampliamente utilizada y de gran utilidad en el análisis de datos. Se representan mediante una gráfica de líneas donde el eje vertical muestra la escala del métrico de interés, como defectos, costos, dimensiones de piezas, quejas de clientes, entre otros. Por otro lado, el eje horizontal representa el tiempo o intervalos en los que se recopilaron los datos. A través de esta representación gráfica, se pueden identificar diversas características y patrones en los datos.

Nos permiten identificar tendencias, ciclos, estacionalidad y cambios de comportamiento en nuestros datos y procesos. Por ejemplo, al observar la distribución de quejas de clientes en una empresa durante los meses de enero a junio, podemos notar que febrero es el mes con más quejas, mientras que abril tiene menos. Esto nos lleva a cuestionarnos qué sucedió en febrero que lo diferencia de abril y cuál podría ser la causa de este comportamiento.

\\subsubsection\*{Componentes principales}

Para analizar estas series, se suelen descomponeren cuatro elementos clave:

\begin{itemize}
 \item{\textbf{Tendencia} El movimiento general a largo plazo de la serie (si sube, baja o se Estacionalidad: mantiene estable). }
 \item{\textbf{Ciclo:} Cambios de larga duración que no tienen un periodo fijo (comunes en ciclos económicos).}
 \item{\textbf{Factor Irregular:}Variaciones aleatorias o impredecibles causadas por eventos inesperados (huelgas, desastres naturales, etc.). }
 \item{\textbf{Estacionalidad:}:  Variaciones  que se repiten en periodos específicos, como el aumento de ventas de juguetes en Navidad.}
\end{itemize}

\

\chapter{Marco Metódico}

En este capítulo se visualizarán todas los procedimientos, pruebas y metodologías estadísticas para sustentar la hipótesis planteada en nuestro trabajo. Se detalla el comportamiento de los datos de Agricultura.cvs, técnicas de limpieza (Data Wrangling) y los tests de inferencia utilizados para determinar la significancia estadística de los tipos de cultivos de la India y su producción. En este análisis utilizaremos el lenguaje de programación R, con el Desarrollo de RStudio, empleando empleando el paradigma “Tidyverse” para la manipulación de datos.\

\section{Bases metódicas utilizadas en el trabajo de investigación}

En la presente investigación fijamos una variable cuantitativa a nivel descriptivo, ya que, se busca caracterizar la situación agrícola procesando datos numéricos de la producción, áreas cultivadas y rendimiento agrícola en la India. Dicho esto se utilizó bases metódicas estadísticas integrando datos cuantitativos y cualitativos.\

\subsubsection{Procesamiento y Limpieza de Datos (ETL)}

En este trabajo se utilizó el procesamiento y limpieza de datos (ETL), el cual se caracteriza por realizar cambios en la data, permitiendo mover información desde múltiples fuentes hacia un solo destino, facilitando así el análisis y comprensión requerido para la realización de nuestros objetivos. En Este caso se utilizó para extraer los datos obtenidos en el dataset Agricultura.csv

Este proceso cuenta de tres fases, como lo son:

\begin{itemize}
 \item{\textbf{La extracción:} Se recopiló los datos del dataset dado Agricultura.csv}
 \item{\textbf{La transformación:} En esta fase  se limpio, ordenó y estandarizo los datos  para obtener información de alta calidad.}
 \item{\textbf{La carga:}Por último  los datos ya procesados se almacenan en un sistema de destino, por lo general en un Data Warehouse (Almacén de datos).}
\end{itemize}

\

\subsubsection{Selección de Datos Necesarios}

En esta fase se filtraron las columnas del dataset Agricultura.csv para realizar de una manera más eficaz el análisis de las variables. En este caso las variables cuantitativas utilizadas fueron: Crop_Year, Crop, State; destacando además variables explicativas como lo son Production, Area y Yield.\

\subsubsection{Verificación de Datos Faltantes}

Con la ayuda de Tidyverse utilizando librerías como los son (“dplyr” y “tidyr”), se escaneo el dataset en busca de valores nulos, acomodando así nuestra data.  

\subsubsection{Categorización de Cultivos y Estados}

Para facilitar el análisis, se agruparon sectores de cultivos creando nueva información colocada en etiquetas. Un cultivo como “Arroz” y “Frijoles” se colocó en la nueva Variable (Crop_Year) como “Cereales y Granos” , permitiendo comparar el crecimiento de cereales básicos con legumbres o cultivos comerciales.\

\subsubsection{Categorización de Cultivos y Estados}

Por último se identificaron anomalías estadísticas, y se utilizaron los métodos estadísticos correspondientes (moda, media, mediana, rango intercuartílico , media aritmética y varianza) para visualizarla de una mejor manera.\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\subsubsection*{REGIONES CON MAYOR Y MENOR PRODUCCIÓN}

Al observar el mapa de calor de la India realizado en el Dashboard, tenemos como resultado una distribución desigual. Las regiones del norte y el centro del país presentan una actividad muy escasa, mientras que el sur y zonas montañosas del país aparecen con color más intenso, lo que nos indica que la producción agrícola es más alta.

Respondiendo así a la pregunta principal ¿Cuáles son las regiones con mayor y menor producción agrícola?.

Los estados con mayor producción se encuentran al sur de la India, teniendo a Kerala como el estado con más de 74000 millones; mientras que Jammu and Kashmir se sitúa como el estado con menor producción agrícola con un total de 63330.

Esto nos permite concluir que la producción está ligada a la geografía, concentrándose en las zonas donde hay mejor tierra y son más altas lo que permite una mejor cosecha.\

\subsubsection*{¿CÓMO HA EVOLUCIONADO LA PRODUCCIÓN Y EL RENDIMIENTO A TRAVÉS DEL TIEMPO?}

El gráfico de evolución temporal, el cual indica la respuesta a nuestro objetivo numero 2, nos muestra un crecimiento constante. Desde 1997 hasta el año 2009, no ha decaído en ningún momento. Aunque se muestran pequeños saltos entre años (subidas y bajadas) probablemente causados por el clima, la tendencia general es muy positiva; demostrando que la India no solo ha mantenido el ritmo de producción, sino que produce cada vez más.\

\subsubsection*{¿CÓMO AFECTA EL TIPO DE CULTIVO EN EL ÁREA CULTIVADA?}

En el análisis de las barras observamos que la papa, el banano y la caña de azúcar son los cultivos que lideran el volumen de producción general. Destacan por su eficiencia y rendimiento por área, ya que producen mucho en poco espacio. Al enfocarse en estos cultivos esto le permite al país tener más ganancias y asegurar alimento para la población. Respondiedno asi a nuestro tercer objetivo planteado en la investigación \

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

